[package]
name = "pomo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"

[dependencies]
termion = "1.5.6"
ctrlc = "3.1.9"
clap = "2.33"
figlet-rs = "0.1"
